---
- name: Install packages
  apt:
    name: "{{ redmine_apache_subversion_packages }}"
    update_cache: yes
    state: latest
    cache_valid_time: 86400
  notify:
  - restart apache

- name: Apache modules
  apache2_module:
    name: "{{ item }}"
  with_flattened:
  - "{{ redmine_apache_subversion_modules }}"
  - "{{ redmine_apache_subversion_https_fix_modules if redmine_apache_subversion_https_fix else [] }}"
  notify:
  - restart apache

- name: Folder
  file:
    dest: "{{ redmine_apache_subversion_folder }}"
    state: directory
    owner: "{{ redmine_apache_subversion_folder_user }}"
    group: "{{ redmine_apache_subversion_folder_group }}"
    mode: "2775" # include the change group bit

- name: Create script
  copy:
    src: "svn_createrep.sh"
    dest: "{{ redmine_apache_subversion_folder }}/{{ redmine_apache_subversion_create_script_name }}"
    mode: "700"
  when: redmine_apache_subversion_create_script_name != ''

- name: Fix permission script
  copy:
    src: "svn_fixpermissions.sh"
    dest: "{{ redmine_apache_subversion_folder }}/{{ redmine_apache_subversion_fix_script_name }}"
    mode: "700"
  when: redmine_apache_subversion_fix_script_name != ''

- name: Apache conf
  template:
    dest: "{{ redmine_apache_subversion_vhost_path }}/{{ redmine_apache_subversion_config_name }}.conf"
    src: "redmine_subversion.conf.j2"
  notify:
  - restart apache
