---
- name: Install packages
  ansible.builtin.apt:
    name: "{{ redmine_apache_auth_packages }}"
    update_cache: true
    state: latest
    cache_valid_time: 86400
  notify: Restart

- name: Authn Folder
  ansible.builtin.file:
    dest: "{{ redmine_apache_auth_file | dirname }}"
    state: directory
    mode: "755"

- name: Create Redmine.pm
  ansible.builtin.get_url:
    url: "{{ redmine_apache_auth_url }}"
    dest: "{{ redmine_apache_auth_file }}"
    mode: "644"
  notify: Restart

- name: Auth conf
  ansible.builtin.template:
    dest: "{{ APACHE_SERVER_CONF_AVAILABLE_PATH }}/{{ redmine_apache_config_name }}.conf"
    src: "redmine_auth.j2"
    mode: "644"
  notify: Restart

- name: Enable auth
  ansible.builtin.command: "a2enconf {{ redmine_apache_config_name }}"
  register: redmine_apache_auth_conf_enable_result
  changed_when: "'Enabling conf' in redmine_apache_auth_conf_enable_result.stdout"
  notify: Restart

# Redmine.pm only works with the prefork model
- name: Enable Prefork
  community.general.apache2_module:
    state: "{{ item.state }}"
    name: "{{ item.name }}"
    ignore_configcheck: true
    warn_mpm_absent: false
  loop:
    - {name: mpm_worker, state: absent}
    - {name: mpm_event, state: absent}
    - {name: mpm_prefork, state: present}
  notify: Restart

- name: Store Facts
  ansible.builtin.set_fact:
    REDMINE_APACHE_AUTH_PERL_PACKAGE: "{{ redmine_apache_auth_perl_package }}"
    REDMINE_APACHE_AUTH_DSN: >-
      {{
      [
        'DBI',
        redmine_apache_auth_database_dbi,
        [
          'database=' + redmine_apache_auth_database_name,
          'host=' + redmine_apache_auth_database_host,
          'port=' + redmine_apache_auth_database_port
        ] | join(';')
      ] | join(':')
      }}
    REDMINE_APACHE_AUTH_DB_USER: "{{ redmine_apache_auth_database_user }}"
    REDMINE_APACHE_AUTH_DB_PASSWORD: "{{ redmine_apache_auth_database_password }}"
  tags: [always]
