---
- name: Add repo
  ansible.builtin.apt_repository:
    repo: "{{ redmine_apache_git_repository }}"
  when: redmine_apache_git_repository | length > 0
  retries: 5
  delay: 3
  register: result
  until: result is not failed

- name: Install packages
  ansible.builtin.apt:
    name: "{{ redmine_apache_git_packages }}"
    update_cache: true
    state: latest
    cache_valid_time: 86400
  notify: Restart

- name: Apache modules
  community.general.apache2_module:
    name: "{{ item }}"
  loop: "{{ [redmine_apache_git_modules, (redmine_apache_git_https_fix_modules if redmine_apache_git_https_fix else [])] | flatten }}"
  notify: Restart

- name: Git Folder
  ansible.builtin.file:
    dest: "{{ redmine_apache_git_folder }}"
    state: directory
    owner: "{{ redmine_apache_git_folder_user }}"
    group: "{{ redmine_apache_git_folder_group }}"
    mode: "2775" # include the change group bit

- name: Create script
  ansible.builtin.copy:
    src: "git_createrep.sh"
    dest: "{{ redmine_apache_git_folder }}/{{ redmine_apache_git_create_script_name }}"
    mode: "700"

- name: Fix permission script
  ansible.builtin.copy:
    src: "git_fixpermissions.sh"
    dest: "{{ redmine_apache_git_folder }}/{{ redmine_apache_git_fix_script_name }}"
    mode: "700"

- name: Apache conf
  ansible.builtin.template:
    dest: "{{ redmine_apache_git_vhost_path }}/{{ redmine_apache_git_config_name }}.conf"
    src: "redmine_git.conf.j2"
    mode: "644"
  notify: Restart
